import type { TemplateOnlyComponent as TOC } from '@ember/component/template-only';
export interface S {
    Args: {
        width?: number;
        height?: number;
        series?: unknown[];
        data?: unknown;
        variant?: string;
        title?: string;
        rotateData?: boolean;
        categoryProperty?: string;
        valueProperty?: string;
        chartStyle?: unknown;
        chartTitleStyle?: unknown;
        maxColumns?: number;
        orientation?: string;
        colorMap?: unknown;
        cellStyle?: unknown;
        cellTitleStyle?: unknown;
        cellTextOverlayStyle?: unknown;
        plotStyle?: unknown;
        categoryAxisScale?: unknown;
        valueAxisScale?: unknown;
        categoryAxisFormatter?: unknown;
        valueAxisFormatter?: unknown;
        categoryAxisSort?: string;
        categoryAxisMaxLabelCount?: number;
        valueAxisMax?: number;
        xAxisFormatter?: unknown;
        yAxisFormatter?: unknown;
        xAxisStyle?: unknown;
        yAxisStyle?: unknown;
        xAxisPointer?: string;
        yAxisPointer?: string;
        xAxisPointerLabel?: string;
        yAxisPointerLabel?: string;
        xAxisPointerStyle?: unknown;
        yAxisPointerStyle?: unknown;
        xAxisPointerLabelStyle?: unknown;
        yAxisPointerLabelStyle?: unknown;
        xAxisTooltip?: unknown;
        yAxisTooltip?: unknown;
        xAxisZoom?: string;
        yAxisZoom?: string;
        xAxisZoomBrush?: boolean;
        yAxisZoomBrush?: boolean;
        xAxisZoomStyle?: unknown;
        yAxisZoomStyle?: unknown;
        legend?: string;
        legendOrientation?: string;
        legendStyle?: unknown;
        drillUpButtonStyle?: unknown;
        drillUpButtonText?: string;
        onSelect?: (item: unknown) => void;
    };
}
declare const TimeSeriesChartComponent: TOC<S>;
export default TimeSeriesChartComponent;
//# sourceMappingURL=time-series.d.ts.map