name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */node_modules
          key: node_modules-${{runner.os}}-${{hashFiles('**/pnpm-lock.yaml')}}-v2
      - name: Install dependencies
        run: CI=true pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

  test-try:
    name: Additional Tests
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        scenario:
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */node_modules
          key: node_modules-${{runner.os}}-${{hashFiles('**/pnpm-lock.yaml')}}-v2
      - name: Install dependencies
        run: CI=true pnpm i --frozen-lockfile
      - name: Test
        run: >-
          node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
          --skip-cleanup
        working-directory: ./test-app
