name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
          key: node_modules-${{runner.os}}-${{hashFiles('**/pnpm-lock.yaml')}}-v2
      - name: Install dependencies
        run: CI=true pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

  try_scenarios:
    name: ${{ matrix.try-scenario }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-3.28
          - ember-4.0.0
          - ember-4.4
          - ember-4.8
          - ember-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */node_modules
          key: node_modules-${{runner.os}}-${{hashFiles('**/pnpm-lock.yaml')}}-v2
      - name: Install dependencies
        run: CI=true pnpm i --frozen-lockfile
      - name: Test
        run: >-
          node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
          --skip-cleanup
        working-directory: ./test-app
